### PR TITLE
Update `embedded-hal` dependencies

### PR DESCRIPTION
**Pull request by romancardenas**
**NOTE:** I still haven't tested these updates on boards. I will keep building some examples to verify that everything is alright. Furthermore, I have a few doubts about some peripherals (especially SPI, namely I don't understand why we would support SPI peripherals with MOSI or MISO missing).

### CODE REVIEW

**Comment by almindor** [comment]
> **NOTE:** I still haven't tested these updates on boards. I will keep building some examples to verify that everything is alright. Furthermore, I have a few doubts about some peripherals (especially SPI, namely I don't understand why we would support SPI peripherals with MOSI or MISO missing).

By MOSI/MISO missing I'm guessing you mean using the `(MOSI, SCK, CS)` kind of tuples? This was done since some devices (e.g. displays) do not use MISO and do not have an actual connector for it.

**Comment by romancardenas** [comment]
So we provide SPI implementation without owning the MISO pin?

The potential problem I see here is that SPI traits usually deal with reading and writing. Maybe we need to re-structure the trait implementation to return errors in those pin configurations that are not complete (e.g., return an Error when trying to read from a display)

**Comment by romancardenas** [comment]
I rescued a few examples from `riscv-quickstart` but adapting them to use semihosting for QEMU emulation. However (surprise) QEMU does not support GPIO on sifive_e targets yet 🥲

**Comment by romancardenas** [comment]
I added new examples. It looks like QEMU supported GPIOs, but I introduced a bug in the GPIO implementation. Current examples work as expected both in QEMU and on board.

Examples are now in `hifive1-examples`. The idea is that `hifive1-examples` can work as `riscv-rust-quickstart` but with all the new configurations. Having all the examples in the same repo as the PAC, HAL, and BSP is useful while developing.

I managed to use semihosting on the board. However, it only works for OpenOCD, JLinkDebugger has this option disabled.
I added a few scripts to facilitate opening a debug session on board. Once I am done testing everything, I will write a nice README file.

**Comment by romancardenas** [comment]
I still need to check:

- [ ] GPIO input traits
- [ ] I2C traits
- [ ] SPI traits

**Comment by romancardenas** [comment]
All the HAL implementations are working now. I still need to implement a few `embedded-io` traits for SPI, I guess.

**Comment by romancardenas** [comment]
@almindor all the `e-h` traits have been implemented and tested with examples that are available in this PR

**Review by almindor — APPROVED** [review]
This was a huge amount of work! Thank you!

**Comment by almindor** [comment]
> @almindor all the `e-h` traits have been implemented and tested with examples that are available in this PR

Do you want to do a 0.11 release right after this is merged?

**Pull request merged**
